### PR TITLE
Added npm install to log after new command

### PR DESCRIPTION
**Pull request by ibandominguez**
Hi there, 

First at all thank you for Adonis, great work, I like the way you picked up all the good patterns from Laravel and ported to Node.

I have just installed the cli globally and run **adonis new project-name**, and followed the given instructions and got this error. 

captura de pantalla 2017-07-13 a las 22 29 14

It took me just a second to realize that I had to install all the required dependencies, so it´s quite implicit but just in case you´d like it to make it explicit I am sending along this pull request.

Cheers, 
Keep up the good work

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @ibandominguez !

The default behaviour of the CLI is to install dependencies and you can avoid that with the `--skip-install` option.

I have tried myself (without updating) the `adonis-cli` (2.1.9) and I got this error.
Must be something with the latest version of `npm`.

Which version are you running?

**Comment by ibandominguez** [comment]
👍

**Comment by RomainLanz** [comment]
The issue is fixed with the next version of the CLI (for Adonis 4.0).
You can use it by installing it directly from Github.

```
$ npm i -g adonisjs/adonis-cli#develop
```

Since 4.0 is around the corner I think we will not fix this issue for the old version of the CLI.

@ibandominguez, @Naoray

**Comment by ibandominguez** [comment]
Great @RomainLanz, 

I am closing this PR, 

Thank you very much!
Ibán

**Pull request closed without merging**
