### PR TITLE
Allow adonis new --blueprint to clone from custom providers #109

### PR DESCRIPTION
**Pull request by PieterVenter7**
not just github
and internal templates

### CODE REVIEW

**Comment by thetutlage** [comment]
How about using this package https://github.com/jonschlinkert/is-git-url

It will also check for URL's ending with `.git/` or `.git `.

**Comment by RomainLanz** [comment]
ping @PieterVenter7

**Comment by PieterVenter7** [comment]
I do apologize for the long turn around time(had a large production sprint) I've made the recommended changes. Thanks for the advise @thetutlage

**Comment by thetutlage** [comment]
Yes, looks nice 😄

**Pull request merged**
